services:
  postgres:
    image: postgres:16
    container_name: tracker-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tracker_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
